CREATE DATABASE IF NOT EXISTS user;
CREATE DATABASE IF NOT EXISTS tale;
CREATE DATABASE IF NOT EXISTS chat;
CREATE DATABASE IF NOT EXISTS custom_tale;

GRANT ALL PRIVILEGES ON user.* TO 'SSAFY'@'%';
GRANT ALL PRIVILEGES ON tale.* TO 'SSAFY'@'%';
GRANT ALL PRIVILEGES ON chat.* TO 'SSAFY'@'%';
GRANT ALL PRIVILEGES ON custom_tale.* TO 'SSAFY'@'%';

FLUSH PRIVILEGES;

