# for KSS section
FROM node:lts-alpine as kss-stage

# FROM python:3.8-bookworm
# install pip
# RUN set -xe \
#     && apt-get update \
#     && apt-get install python3-pip
# COPY src/main/java/com/ssafy/tosi/taleDetail/morpheme/kss.py kss.py
# RUN pip install kss --verbose


FROM eclipse-temurin:17-jdk-alpine

# Install Python and Node.js
# RUN apk add --no-cache python3 py3-pip nodejs npm

# RUN apk add --no-cache nodejs npm
# RUN apt-get update -y && apt-get install python3

# install node
# RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
#     apt-get install -y nodejs

CMD ["./mvnw", "clean", "package"]
COPY target/tosi-0.0.1-SNAPSHOT.jar app.jar

VOLUME /tmp

ENTRYPOINT ["java","-Djava.library.path=/home/ubuntu/kiwilib/","-jar","/app.jar"]

EXPOSE 8080