spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/user?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    hikari:
      idle-timeout: 300000
      max-lifetime: 1800000
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    output:
      ansi.enabled: always
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB
  data:
    redis:
      port: 6379
      host: redis
logging:
  level:
    org.springframework.data.redis.cache: DEBUG
jwt:
  secret: f671835008b1cea40c25b3743721b37428ad5124e631044a240bd5915dcf059c02ccd1ac0cc2f17df0654c6e85982a132a06f98e2ba199d2e1323a5dcdf8263f
server:
  port: 8081
service:
  tale:
    url: ${TALE_URL}
